services:
  apizafreader:
    build: .
    command: uvicorn main:app --port 8501 --host 0.0.0.0 --reload
    volumes:
      - .:/app
      - ./key.json:/tmp/credentials.json
    ports:
      - "8501:8501"
    environment:
      - NAME=World
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json      